# Generated by Django 3.2 on 2021-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credibility_score', models.FloatField()),
                ('relevancy_score', models.FloatField()),
                ('nonopinion_score', models.FloatField()),
                ('nonsatire_score', models.FloatField()),
                ('nonsensational_score', models.FloatField()),
                ('topic', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
