# Generated by Django 3.2 on 2021-09-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsOutlet', '0001_initial'),
        ('article', '0003_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='outletId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newsOutlet.newsoutlets'),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=None),
        ),
    ]
