# Generated by Django 3.2 on 2021-09-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_outletid_article_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
