# Generated by Django 3.2 on 2021-05-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='opinion_score',
            new_name='nonopinion_score',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sattire_score',
            new_name='nonsatire_score',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sensational_score',
            new_name='nonsensational_score',
        ),
    ]
