# Generated by Django 3.2 on 2021-05-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
    ]
