# Generated by Django 3.2 on 2021-09-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOutlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credibility_score', models.FloatField()),
                ('outlet_name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
