# Generated by Django 3.2 on 2021-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsOutlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsoutlets',
            name='totalScore',
            field=models.FloatField(default=None),
        ),
    ]
