# Generated by Django 3.2 on 2021-09-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsOutlet', '0002_newsoutlets_totalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsoutlets',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
