# Generated by Django 3.2 on 2021-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210526_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
