# Generated by Django 3.1.7 on 2021-09-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_keywords_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
